<?php
/** @var $block \Magento\Sales\Block\Order\Email\Items */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$giftMessageHelper = $objectManager->get(\Magento\GiftMessage\Helper\Message::class);
?>
<?php $order = $block->getOrder() ?>
<?php if ($order): ?>
    <?php $_items = $order->getAllItems(); ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-image">
                <?= /* @noEscape */ __('Image') ?>
            </th>
            <th class="item-info">
                <?= /* @noEscape */  __('Items') ?>
            </th>
            <th class="item-qty">
                <?= /* @noEscape */  __('Qty') ?>
            </th>
            <th class="item-price">
                <?= /* @noEscape */  __('Price') ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getParentItem()): ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($giftMessageHelper->isMessagesAllowed('order', $order, $order->getStore())
        && $order->getGiftMessageId()): ?>
        <?php $giftMessage = $giftMessageHelper->getGiftMessage($order->getGiftMessageId()) ?>
        <?php if ($giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @noEscape */ __('Gift Message for this Order') ?></h3>
                        <strong><?= /* @noEscape */ __('From:') ?></strong>
                        <?= $block->escapeHtml($giftMessage->getSender()) ?>
                        <br /><strong><?= /* @noEscape */ __('To:') ?></strong>
                        <?= $block->escapeHtml($giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @noEscape */ __('Message:') ?></strong>
                        <br /><?= $block->escapeHtml($giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
