<?php

$productId = (int)$block->getRequest()->getParam('product', 0);
$baseUrl   = $block->getBaseUrl();
?>


<div id="product-builder" shop-name="<?php echo $baseUrl; ?>" product-id="<?php echo $productId; ?>" styles-path="//cdn.shopify.com/s/files/1/1520/2864/t/16/assets/customproductbuilder.css?622266423132693063" admin="true" engine="magento">
    Loading ...
</div>
<?php
/*
<script type="text/javascript" src="https://customproductbuilder.buildateam.io/dist/custom-product-builder.js?"></script>
*/ ?>

<script> jQuery.getScript('http://localhost:8082/dist/custom-product-builder.js'); </script>