<?php

?>


<div id="product-builder" shop-name="bucket-hats-4.myshopify.com" product-id="10156854920" styles-path="//cdn.shopify.com/s/files/1/1520/2864/t/16/assets/customproductbuilder.css?622266423132693063" admin="true" engine="magento">
    Loading ...
</div>
<?php /*
<script type="text/javascript" src="https://customproductbuilder.buildateam.io/dist/custom-product-builder.js?"></script>
*/ ?>

<script> jQuery.getScript('https://customproductbuilder.buildateam.io/dist/custom-product-builder.js'); </script>