<?php
// @codingStandardsIgnoreFile
?>
<?php /** @var \Magento\Sales\Block\Adminhtml\Order\View\Items\Renderer\DefaultRenderer $block */ ?>
<?php $_item = $block->getItem() ?>
<?php $block->setPriceDataObject($_item) ?>
<tr>
    <td>
        <?php $product = $_item->getProduct(); ?>
        <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>

        <?php $imageHelper = $objectManager->get('\Magento\Catalog\Helper\Image'); ?>
        <?php $imageUrl = $imageHelper->init($product, 'small_image')->setImageFile($product->getSmallImage())->resize(200, 200)->getUrl(); ?>
        <img src="<?= $block->escapeUrl($imageUrl); ?>" style="min-width: 100px"/>
    </td>
    <?php $i = 0;
    $columns = $block->getColumns();
    $lastItemNumber = count($columns) ?>
    <?php foreach ($columns as $columnName => $columnClass): ?>
        <?php $i++; ?>
        <td class="<?= /* @noEscape */
        $columnClass ?><?= /* @noEscape */
        ($i === $lastItemNumber ? ' last' : '') ?>"><?= /* @escapeNotVerified */
            $block->getColumnHtml($_item, $columnName) ?></td>
    <?php endforeach; ?>
</tr>
