<?php
/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */
/** @var $item \Magento\Sales\Model\Order\Item */
$item = $block->getItem();
$product =  $item->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imageHelper = $objectManager->get(\Magento\Catalog\Helper\Image::class);
$imageUrl = $imageHelper->init($product, 'small_image')->setImageFile($product->getSmallImage())
    ->resize(200, 200)->getUrl();
?>
<tr>
    <td class="item-image"><img src="<?= /* @noEscape */ $imageUrl ?>" style="min-width: 100px"/></td>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($item->getName()) ?></p>
        <p class="sku"><?= /* @noEscape */ __('SKU') ?>: <?= $block->escapeHtml($block->getSku($item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= /* @noEscape */ $option['label'] ?></em></strong></dt>
                    <dd>
                        <?= /* @noEscape */ nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?= $addInfoBlock->setItem($item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($item) ?>
    </td>
</tr>
<?php if ($item->getGiftMessageId() && $giftMessage = $objectManager->get(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($item->getGiftMessageId())): ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @noEscape */ __('Gift Message') ?></h3>
                        <strong><?= /* @noEscape */ __('From:') ?></strong>
                        <?= $block->escapeHtml($giftMessage->getSender()) ?>
                        <br /><strong><?= /* @noEscape */ __('To:') ?></strong>
                        <?= $block->escapeHtml($giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @noEscape */ __('Message:') ?></strong>
                        <br /><?= $block->escapeHtml($giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
